sonar.projectKey=ovgu-lendingsystem
sonar.projectName=OvGU LendingSystem
sonar.host.url=http://127.0.0.1:9000
sonar.sourceEncoding=UTF-8

sonar.sources=backend,frontend/src,frontend/Dockerfile,frontend/nginx,docker-compose.yml,compose.tls.yml
sonar.exclusions=**/node_modules/**,**/build/**,backend/alembic/**,**/__pycache__/**,backend/Tests/**,frontend/src/**/*.test.tsx,**/*.png,**/*.jpg,**/*.pdf
sonar.tests=backend/Tests,frontend/src
sonar.test.inclusions=backend/Tests/**,frontend/src/**/*.test.tsx
sonar.python.version=3.12
